### ISSUE TITLE
Demo Kubernetes Deployment

### ISSUE THREAD

**Issue by jasonmimick** [mongodb/atlas-osb#31]
The Atlas Service Broker can be deployed into Kubernetes and utilized through the Service Catalog framework.
This issue will track an effort to add a new workflow and build pipeline to a Kubernetes cluster.

**Comment by jasonmimick** [comment]
**Draft Design**

Goal: Demonstrate a Kubernetes based deployment of atlas-osb. Integrate Service Catalog and CI/CD tooling for both broker (dbaas) and customer usage (sample applications creating and using database services).

Use
- Docker to package the controller runtime
- Kubernetes to host the runtime
- Helm to install the controller into Kubernetes
- Service Catalog for Marketplace 
- GitHub Actions/Argo Workflows to orchestrate the whole thing (post Phase 1)
- KubeApps or similar for fancy UI (post Phase 1)

**Phase 1) Deploy to static EKS cluster**

For first phase, we will have 1 GitHub workflow which will:
1. Build the Docker image
2. Push the Docker image to AWS ECR
3. Run `helm install atlas-osb` - install 1 helm chart for the broker
4. Run `helm install demo-service-1` install 1 helm chart which creates a Basic Plan with the broker and connects a sample app
to push an update to the broker.

This will all target a fixed EKS cluster in AWS, use integration for `kubectl` in the action via GitHub Secrets. (For example, store `KUBECONFIG` from `aws eks ...` command in a secret, something simple like that.)

**Comment by jasonmimick** [comment]
TODO List
====
- [ ] Create EKS Cluster
- [ ] Install Service Catalog
- [ ] Add GitHub Secret
- [ ] Verify can run action locally, e.g. `act -j eks-demo` 

@vasilevp & @leo-ri  we can use this to keep track of what's setup/needed still.
Can you please edit this ticket/add notes with info on the EKS cluster, any design considerations, etc?
